import Link from 'next/link';

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Link href="/" className="font-bold text-xl text-gray-900">
              Idea Feedback
            </Link>
            <Link 
              href="/" 
              className="px-4 py-2 text-sm font-medium text-gray-700 hover:text-gray-900"
            >
              Back to Home
            </Link>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-lg shadow-sm p-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
          
          <div className="prose prose-gray max-w-none">
            <p className="text-gray-600 mb-6">
              <strong>Effective Date: December 18, 2024</strong><br/>
              <strong>Last Updated: December 18, 2024</strong>
            </p>

            <div className="bg-blue-50 border-l-4 border-blue-400 p-4 mb-6">
              <p className="text-blue-700 font-semibold">Chrome Web Store Limited Use Disclosure</p>
              <p className="text-blue-700 mt-2">
                Idea Feedback's use and transfer of information received from Google APIs and Chrome Extension APIs 
                adheres to the Chrome Web Store User Data Policy, including the Limited Use requirements.
              </p>
            </div>

            <h2 className="text-2xl font-semibold mt-8 mb-4">1. Information We Collect</h2>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">1.1 Information You Explicitly Provide</h3>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Account Information:</strong> When you sign up via Clerk authentication, we collect your email address, name (optional), and generate a unique user ID</li>
              <li><strong>API Keys:</strong> Your OpenAI API key (stored locally in your browser extension storage only, never transmitted to our servers)</li>
              <li><strong>Interview Content:</strong> Interview titles, interviewee names, companies, and roles that you manually enter</li>
              <li><strong>User-Generated Notes:</strong> Any notes or annotations you add during interviews</li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3">1.2 Information Automatically Collected During Interviews</h3>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Interview Transcripts:</strong> Audio-to-text transcriptions from video calls (processed locally via Web Speech API when possible)</li>
              <li><strong>Timestamps:</strong> Start time, end time, and duration of interviews</li>
              <li><strong>Meeting URLs:</strong> The video conferencing platform URLs (Google Meet, Zoom) to detect when to activate the extension</li>
              <li><strong>AI-Generated Content:</strong> Suggestions, summaries, and feature ideas generated by OpenAI based on your interview content</li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3">1.3 Web Browsing Activity</h3>
            <p className="mb-4">
              <strong>Important:</strong> We only access web browsing activity that is directly related to our core functionality:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Video Conference Detection:</strong> We detect when you're on supported platforms (meet.google.com, zoom.us) to enable interview features</li>
              <li><strong>LinkedIn Research:</strong> When you explicitly click "Research" and provide a LinkedIn URL, we access that specific page to gather professional background information</li>
              <li><strong>No Background Tracking:</strong> We do NOT collect browsing history, monitor other tabs, or track your general web activity</li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3">1.4 Technical Information</h3>
            <ul className="list-disc pl-6 mb-4">
              <li>Extension version number</li>
              <li>Browser type and version (for compatibility)</li>
              <li>Error logs related to extension functionality</li>
              <li>Performance metrics (interview count, feature usage statistics)</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">2. How We Use Your Information</h2>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">2.1 Primary Uses (User-Facing Features)</h3>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Interview Assistance:</strong> Provide real-time AI suggestions during interviews</li>
              <li><strong>Transcription:</strong> Convert speech to text for review and analysis</li>
              <li><strong>Research:</strong> Gather publicly available professional information when you request it</li>
              <li><strong>Summaries:</strong> Generate meeting recaps and action items</li>
              <li><strong>Data Sync:</strong> Sync your interviews between the extension and web dashboard</li>
              <li><strong>Authentication:</strong> Verify your identity and maintain your session</li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3">2.2 Prohibited Uses</h3>
            <p className="mb-4">We explicitly DO NOT use your data for:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>❌ Advertising or marketing purposes</li>
              <li>❌ Selling or renting to third parties</li>
              <li>❌ Behavioral profiling or tracking</li>
              <li>❌ Any purpose unrelated to interview assistance</li>
              <li>❌ Training AI models (your data is not used to train OpenAI or any other models)</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">3. Data Storage and Security</h2>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">3.1 Where Your Data is Stored</h3>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Local Browser Storage:</strong> 
                <ul className="list-disc pl-6 mt-2">
                  <li>OpenAI API key (encrypted)</li>
                  <li>User preferences and settings</li>
                  <li>Temporary interview data before sync</li>
                </ul>
              </li>
              <li><strong>Supabase Database:</strong> 
                <ul className="list-disc pl-6 mt-2">
                  <li>User profiles (synced from Clerk)</li>
                  <li>Interview transcripts and metadata</li>
                  <li>AI-generated summaries and notes</li>
                  <li>All database access uses Row Level Security (RLS)</li>
                </ul>
              </li>
              <li><strong>Clerk Authentication:</strong> 
                <ul className="list-disc pl-6 mt-2">
                  <li>Authentication tokens</li>
                  <li>Email and profile information</li>
                </ul>
              </li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3">3.2 Security Measures</h3>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Encryption in Transit:</strong> All data transmitted using HTTPS/TLS 1.3</li>
              <li><strong>Encryption at Rest:</strong> Database encrypted using AES-256</li>
              <li><strong>Access Control:</strong> Row Level Security ensures users only access their own data</li>
              <li><strong>API Key Security:</strong> OpenAI keys never leave your browser</li>
              <li><strong>No Password Storage:</strong> Authentication handled by Clerk's secure infrastructure</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">4. Chrome Extension Specific Permissions</h2>
            
            <p className="mb-4">Our extension requires these permissions for the following specific purposes:</p>
            
            <div className="bg-gray-50 p-4 rounded-lg mb-4">
              <h4 className="font-semibold mb-2">Required Permissions:</h4>
              <ul className="list-disc pl-6">
                <li><strong>storage:</strong> Save your preferences and interview data locally</li>
                <li><strong>tabs:</strong> Detect when you're on video conferencing sites</li>
                <li><strong>activeTab:</strong> Inject the interview sidebar into your current tab when activated</li>
                <li><strong>scripting:</strong> Add interview UI elements to video call pages</li>
                <li><strong>webNavigation:</strong> Detect navigation to supported video platforms</li>
                <li><strong>offscreen:</strong> Process audio streams for transcription in the background</li>
              </ul>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg mb-4">
              <h4 className="font-semibold mb-2">Host Permissions (only these specific sites):</h4>
              <ul className="list-disc pl-6">
                <li><strong>meet.google.com:</strong> Enable interview features on Google Meet</li>
                <li><strong>zoom.us:</strong> Enable interview features on Zoom</li>
                <li><strong>teams.microsoft.com:</strong> Enable interview features on Teams</li>
                <li><strong>linkedin.com:</strong> Research feature (only when you explicitly request)</li>
                <li><strong>ideafeedback.co:</strong> Sync data with your dashboard</li>
                <li><strong>api.openai.com:</strong> Send transcripts for AI processing (using your API key)</li>
              </ul>
            </div>

            <h2 className="text-2xl font-semibold mt-8 mb-4">5. Third-Party Services and Data Sharing</h2>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">5.1 Service Providers We Use</h3>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Clerk (Authentication):</strong> Manages user accounts and sign-in. See <a href="https://clerk.com/privacy" className="text-blue-600 hover:underline" target="_blank">Clerk's Privacy Policy</a></li>
              <li><strong>OpenAI (AI Processing):</strong> Processes transcripts using YOUR API key. Data sent directly from your browser. See <a href="https://openai.com/privacy" className="text-blue-600 hover:underline" target="_blank">OpenAI's Privacy Policy</a></li>
              <li><strong>Supabase (Database):</strong> Stores interview data securely. See <a href="https://supabase.com/privacy" className="text-blue-600 hover:underline" target="_blank">Supabase's Privacy Policy</a></li>
              <li><strong>Vercel (Hosting):</strong> Hosts our web application. See <a href="https://vercel.com/privacy" className="text-blue-600 hover:underline" target="_blank">Vercel's Privacy Policy</a></li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3">5.2 When We Share Data</h3>
            <p className="mb-4">We share your data ONLY in these specific circumstances:</p>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>With OpenAI:</strong> When you use AI features (transcripts sent using your API key)</li>
              <li><strong>Legal Requirements:</strong> If required by law, court order, or legal process</li>
              <li><strong>Safety:</strong> To prevent fraud, abuse, or security threats</li>
              <li><strong>Business Transfer:</strong> If we're acquired or merged (with notice to users)</li>
              <li><strong>With Your Consent:</strong> Only when you explicitly authorize it</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">6. Your Rights and Controls</h2>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">6.1 You Can Always:</h3>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Access Your Data:</strong> View all your interviews and notes in the dashboard</li>
              <li><strong>Export Your Data:</strong> Download your interviews in JSON format</li>
              <li><strong>Delete Specific Items:</strong> Remove individual interviews or notes</li>
              <li><strong>Delete Everything:</strong> Use "Clear All Data" in extension settings</li>
              <li><strong>Revoke Permissions:</strong> Uninstall the extension at any time</li>
              <li><strong>Opt-Out:</strong> Disable specific features in settings</li>
              <li><strong>Update Information:</strong> Change your profile details</li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3">6.2 Data Portability</h3>
            <p className="mb-4">
              You can export all your data at any time through the dashboard. We provide data in standard JSON format that can be imported into other tools.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">7. Data Retention</h2>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Active Accounts:</strong> Data retained as long as your account is active</li>
              <li><strong>Deleted Items:</strong> Removed immediately from our database</li>
              <li><strong>Account Deletion:</strong> All data deleted within 30 days of account closure</li>
              <li><strong>Local Storage:</strong> Cleared immediately when you sign out or clear extension data</li>
              <li><strong>Backups:</strong> Deleted from backups within 90 days</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">8. Children's Privacy</h2>
            <p className="mb-4">
              Idea Feedback is not intended for users under 13 years of age. We do not knowingly collect personal information from children under 13. If we discover we've inadvertently collected such information, we will delete it immediately.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">9. International Data Transfers</h2>
            <p className="mb-4">
              Your data may be processed in the United States and other countries where our service providers operate. We ensure appropriate safeguards are in place for international transfers, including:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>Standard Contractual Clauses for EU data transfers</li>
              <li>Compliance with Privacy Shield principles where applicable</li>
              <li>Encryption of all data in transit and at rest</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">10. Compliance with Privacy Regulations</h2>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">10.1 GDPR (European Users)</h3>
            <p className="mb-4">If you're in the EEA, you have these additional rights:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Right to access your personal data</li>
              <li>Right to rectification of inaccurate data</li>
              <li>Right to erasure ("right to be forgotten")</li>
              <li>Right to restrict processing</li>
              <li>Right to data portability</li>
              <li>Right to object to processing</li>
              <li>Right to withdraw consent at any time</li>
            </ul>
            <p className="mb-4"><strong>Legal Basis:</strong> We process your data based on consent (for optional features) and legitimate interests (for core functionality).</p>

            <h3 className="text-xl font-semibold mt-6 mb-3">10.2 CCPA (California Users)</h3>
            <p className="mb-4">California residents have the right to:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Know what personal information we collect</li>
              <li>Know if personal information is sold or disclosed (we don't sell your data)</li>
              <li>Opt-out of the sale of personal information (not applicable as we don't sell data)</li>
              <li>Access and delete personal information</li>
              <li>Non-discrimination for exercising privacy rights</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">11. Chrome Web Store Compliance</h2>
            <p className="mb-4">
              We comply with all Chrome Web Store policies including:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Minimum Permissions:</strong> We only request permissions necessary for current features</li>
              <li><strong>Single Purpose:</strong> Our extension has one purpose - AI-powered interview assistance</li>
              <li><strong>Prominent Disclosure:</strong> All data collection is clearly related to our stated functionality</li>
              <li><strong>No Hidden Features:</strong> All features are documented and user-facing</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">12. Updates to This Policy</h2>
            <p className="mb-4">
              We may update this Privacy Policy to reflect changes in our practices or for legal reasons. We will notify you of significant changes by:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>Posting a notice in the extension</li>
              <li>Sending an email to registered users</li>
              <li>Updating the "Last Updated" date</li>
            </ul>
            <p className="mb-4">
              Continued use after changes constitutes acceptance of the updated policy.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">13. Contact Us</h2>
            <p className="mb-4">
              For privacy concerns, data requests, or questions about this policy:
            </p>
            <ul className="list-none mb-4">
              <li><strong>Email:</strong> privacy@ideafeedback.co</li>
              <li><strong>Website:</strong> https://ideafeedback.co</li>
              <li><strong>Response Time:</strong> Within 48 hours for urgent privacy matters</li>
            </ul>

            <div className="mt-12 p-6 bg-blue-50 rounded-lg">
              <h3 className="text-lg font-semibold mb-3">Privacy Commitment</h3>
              <p className="text-gray-700">
                We are committed to protecting your privacy and being transparent about our data practices. 
                We follow privacy-by-design principles and continuously review our practices to ensure your data is secure.
              </p>
              <ul className="list-disc pl-6 mt-3 text-gray-700">
                <li>We never sell your data</li>
                <li>We use encryption everywhere</li>
                <li>We minimize data collection</li>
                <li>We give you full control</li>
                <li>We're transparent about our practices</li>
              </ul>
            </div>

            <div className="mt-8 p-4 bg-gray-100 rounded text-sm text-gray-600">
              <p><strong>Document Version:</strong> 2.0</p>
              <p><strong>Last Review:</strong> December 18, 2024</p>
              <p><strong>Next Review:</strong> March 18, 2025</p>
              <p><strong>Data Protection Officer:</strong> privacy@ideafeedback.co</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}